spring:
  application:
    name: sentiment-analysis
  ai:
    vertex:
      ai:
        gemini:
          project-id: statement-analysis-455612
          location: us-central1
          chat:
            options:
              model: gemini-2.5-pro-exp-03-25 #gemini-2.0-flash-001
              tool-calling-enabled: true
        embedding:
          project-id: statement-analysis-455612
          location: us-central1
          text:
            options:
              model: text-embedding-005
              dimensions: 768
              auto-truncate: false
              task_type: SEMANTIC_SIMILARITY

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  # Prevents Hibernate from creating tables
    properties:
      hibernate:
        format_sql: true  # Formats SQL logs for readability
        show_sql: true    # Logs SQL queries in console (optional)



google:
  search:
    api-key: ${GOOGLE_SEARCH_API_KEY}
    engine-id: ${GOOGLE_SEARCH_ENGINE_ID}



